const config = {
  aboutMe:
    "Hello! Welcome to my website. I am Anthony, a software developer with a passion for the craft. I graduated top of my class from two well regarded bootcamps and have been in software development for 6+ years now. I am always learning new things and trying out new technologies. Most recently I have been working on training AI. Please take a look at some of my projects and feel free to reach out to me!",
  projects: [
    {
      id: 0,
      title: "SpaceR2",
      brief:
        "SpaceR2 is a React Native app designed to collect and display real time space related data such as ISS location, astronauts in space, and other information.",
      description:
        "SpaceR was originally my capstone project from ZipCode Wilmington. I worked with another student there to build an app to collate and display various space based information. We had originally built the app in Angular and Java. SpaceR2 was the product of me revisitng this app. I rebuilt the frontend in React and the backend in C# to gain some more knowledge and experience with those technologies. The backend runs on an AWS EC2 instance and stores information is gathers from various APIs in it's database. The front end app is able to be run on Android or IOS and allows the user to view information such as the ISS Location, what astronauts are currently in space, information on upcoming space launces, and more.",
      challenges:
        "Rebuilding a project in a whole new language was something new to me. It was also one of the few times I have rewritten another persons code, as I had to migrate the code my partner had written previously. Overall though, C# and ASP.NET were not too different from Java and Spring Boot, and I found React much easier to work with than Angular was in the original, though I am sure I owe much of that to my own improved skills in the years between.",
      tech: "JavaScript, Java, C#, HTML/CSS, React Native, Angular, Spring Boot, ASP.NET, MVC, AWS EC2, ORM, API",
      github: [
        "https://github.com/AnthonyJordan/SpaceR2Frontend",
        "https://github.com/AnthonyJordan/SpaceR2Backend",
      ],
      ssLocs: [
        { ss0: require("./images/projectImages/spaceR/spaceR0.png") },
        { ss1: require("./images/projectImages/spaceR/spaceR1.png") },
        { ss2: require("./images/projectImages/spaceR/spaceR2.png") },
        { ss3: require("./images/projectImages/spaceR/spaceR3.png") },
      ],
    },
    {
      id: 1,
      title: "Hotherym Gallery",
      brief:
        "A gallery built to display clients art and integrating with their prexisting website and hosting setup.",
      description:
        "My client had a prexisting old website that they had had created long ago. They wished to add a gallery to it to display their art. I built this gallery in React with some light input from the client. I also fixed a few CSS issue and updated some parts of their old website. They were quite happy.",
      challenges:
        "My clients hosting structure was very unique, and finding a way display the art according to the clients specifications was a fun and interesting experience. Integrating with their current website was definitely a challenge due to how it was hosted, but I learned a lot and we were both very happy with the result.",
      tech: "HTML/CSS, JavaScript, React",
      github: ["https://github.com/AnthonyJordan/Hotherym-Original"],
      ssLocs: [
        { ss0: require("./images/projectImages/hotherym/hotherym0.PNG") },
        { ss1: require("./images/projectImages/hotherym/hotherym1.PNG") },
        { ss2: require("./images/projectImages/hotherym/hotherym2.PNG") },
      ],
    },
    {
      id: 2,
      title: "Final Fantasy XIV Free Company Website",
      brief:
        "A website built to display members of guilds in the popular MMORPG Final Fantasy 14. Allows users to create accounts, upload images, build profiles for their characters, and more.",
      description:
        "I built this website as my capstone project for graduating Flatiron. A friend of mine asked me to build a website so that he could display information for him and his friends characters. I built this in Ruby for the backend and React for the frontend. It allows for users to display information on their characters, upload screenshots, comment, and more. It includes password hashing and reset functions as well as allowing visitors to view images and comments generated by users. This was a very fun project and one of the larger things I have built.",
      challenges:
        "As this was a multipage website with user generated content, a storage database, and a password reset mailer, it was a very large undertaking. Particularly setting up the mailer was very new to me. This project really allowed me to flex my web development skills and challenged me with building many different pieces of a greater whole.",
      tech: "Ruby, JavaScript, HTML/CSS, Ruby on Rails, React, MVC, API",
      github: [
        "https://github.com/AnthonyJordan/ffxiv_fc_website_frontend",
        "https://github.com/AnthonyJordan/ffxiv_fc_website_backend2",
      ],
      ssLocs: [
        { ss0: require("./images/projectImages/usagi/usagi0.png") },
        { ss1: require("./images/projectImages/usagi/usagi1.png") },
        { ss2: require("./images/projectImages/usagi/usagi2.png") },
        { ss3: require("./images/projectImages/usagi/usagi3.png") },
        { ss4: require("./images/projectImages/usagi/usagi4.png") },
      ],
    },
  ],
  certifications: [
    {
      id: 0,
      name: "AWS Certified Cloud Practitioner",
      image: require("./images/AWSCert1.jpg"),
    },
    {
      id: 1,
      name: "CompTIA Security+",
      image: require("./images/Security+Cert.jpg"),
    },
  ],
};
export default config;
